### ISSUE TITLE
Fatal error: aes.h: No such file or directory

### ISSUE THREAD

**Issue by BlueMona** [nullsecuritynet/tools#12]
I am attempting to compile using mingw as follows and I get an error regarding a missing header file: 

~# /usr/bin/i686-w64-mingw32-gcc-win32 Hyperion-2.2/Src/Crypter/*.c -o hyperion.exe
Hyperion-2.2/Src/Crypter/encryption.c:6:10: fatal error: aes.h: No such file or directory
 #include <aes.h>
          ^~~~~~~
compilation terminated.

**Comment by b3lial** [comment]
1. Use the Makefile
2. If you really want to build it yourself, add the TinyAES path to your include directory

**Comment by KaliCalm** [comment]
Hi 
I have included TinyAES path but still same issue. 
![image](https://user-images.githubusercontent.com/64976166/85976577-86093600-b9f8-11ea-80e3-fc8e0af35d31.png)

**Comment by Heisenberg0391** [comment]
no need to build it yourself, change the default compiler to i686-w64-mingw32-gcc in makefile should do it.
