### ISSUE TITLE
sshtrix fails to compile against libssh 0.8.0

### ISSUE THREAD

**Issue by DomT4** [nullsecuritynet/tools#6]
I don't know if y'all are planning to support `libssh` 0.8.0 given it removes support for SSHv1, but upstream removed the separate `ssh_threads` library which is currently the only thing breaking compile due to it's presence in the [Makefile](https://github.com/nullsecuritynet/tools/blob/c59b48305f9ede7e6e434d7feff5d678ef73e668/cracker/sshtrix/source/Makefile#L70). Remove that and it builds fine.

Happy to submit a PR but thought it was worth asking about the intention to support new `libssh` versions first.

**Comment by noptrix** [comment]
thanks @DomT4. i will fix this

**Comment by DomT4** [comment]
Apologies, missed your edit until I manually checked through my various open issues today. Opened https://github.com/nullsecuritynet/tools/pull/7.
